=head1 NAME

Riak::Tiny - Lightweight interface to Riak

=head1 USAGE

    my $r = Riak::Tiny->new( host => 'http://localhost:8098' );

Keys

    my $obj = $r->new_object(bucket => key => 'value');
    say $obj->bucket, $obj->key, $obj->value;

Buckets

    my $bucket = $r->bucket('bucket');
    say $_ for $bucket->keys;

    $bucket->delete_keys;

Links

    $obj->add_link(
        tag1 => 'bucket/key2',
        tag2 => 'bucket/key3',
    );

    # Get links
    my ($tag1, $tag2) = $obj->links;
    print $tag1->tag, $tag2->tag;

    # Linked-to key
    my $obj1 = $tag1->linked_to;
    print $obj1->bucket, $obj1->key, $obj1->value;

    $obj->clear_links;

=cut
